### PR TITLE
Make unmanaged libraries bundle correctly for other OS

### PR DESCRIPTION
**Pull request by yellowberryHN**

### CODE REVIEW

**Comment by yellowberryHN** [comment]
So far it works for compiling builds for the target OS if running on the target OS, but does not yet work for cross-compilation, still looking into it.

**Comment by cg505** [comment]
plus one

**Comment by Raymonf** [comment]
@yellowberryHN You'll probably want to check `$(RuntimeIdentifier)` for publishing (so-called cross-compilation)

**Comment by yellowberryHN** [comment]
@Raymonf thanks for the tip! I had seen that before, but I didn't know what it meant by publishing.

**Pull request merged**
